version: "3.9"
services:
  seq:
    image: datalust/seq:latest
    deploy:
      resources:
        limits:
          memory: 14G
        reservations:
          memory: 14G
    ports:
      - 5341:80
    volumes:
      - /var/lib/seq:/var/lib/seq
    environment:
      - ACCEPT_EULA=Y
  rabbitmq:
    image: rabbitmq:3.6.14-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  database_mysql:
    platform: linux/x86_64
    #Pull the latest mysql image
    image: mysql:8.0.22
    #Map port 3306 on the mysql container to port 3306 in the host
    ports:
      - "8778:3306"
    #Specify where the persisted Data should be stored
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    restart: always
    #Specify Environment Variables for mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: newuser
      MYSQL_PASSWORD: newuser
      MYSQL_DATABASE: pretty-reference
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  crawler:
    build:
      context: ./PrettyReference.Backend/src/services/PrettyReference.Crawler/
      dockerfile: PrettyReference.Crawler/Dockerfile
    tty: true
    environment:
      RABBITMQ_HOST: rabbitmq
  reference-manager:
    build:
      context: ./PrettyReference.Backend/src/services/
      dockerfile: PrettyReference.ReferenceManager/PrettyReference.ReferenceManager/Dockerfile
    tty: true
    depends_on:
      database_mysql:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL: server=database_mysql,8778;database=pretty-reference;uid=root;pwd=root    