version: "3.9"
services:
  #  seq:
  #    image: datalust/seq:latest
  #    ports:
  ##      - "5341:5341"
  #      - "80:80"
  rabbitmq:
    image: rabbitmq:3.6.14-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  database_mysql:
    platform: linux/x86_64
    #Pull the latest mysql image
    image: mysql:8.0.22
    #Map port 3306 on the mysql container to port 3306 in the host
    ports:
      - "8778:3306"
    #Specify where the persisted Data should be stored
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    restart: always
    #Specify Environment Variables for mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: newuser
      MYSQL_PASSWORD: newuser
      MYSQL_DATABASE: pretty-reference
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  crawler:
    build:
      context: ./backend/Crawler/PrettyReference.Crawler
      dockerfile: PrettyReference.Crawler/Dockerfile
    tty: true
    depends_on:
      database_mysql:
        condition: service_healthy
