

export const CREATE_TOPIC = 'CREATE_TOPIC'


export const CREATE_SUB_TOPIC = 'CREATE_SUB_TOPIC'
export const SET_ACTUAL_SUB_TOPIC = 'SET_ACTUAL_SUB_TOPIC'


export const CREATE_CARD = 'ADD_CARD'


export const SET_WINDOW_SETTINGS_STATE = 'SET_WINDOW_SETTINGS_STATE'

export const SET_CANDIDATE_FOR_DELETION = 'SET_CANDIDATE_FOR_DELETION'
export const UNSET_CANDIDATE_FOR_DELETION = 'UNSET_CANDIDATE_FOR_DELETION'

export const DELETE_CANDIDATE_FOR_DELETION = 'DELETE_CANDIDATE_FOR_DELETION'